version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: user_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - user_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build: .
    container_name: user_api
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: user_db
      DB_USER: root
      DB_PASSWORD: password
      JWT_SECRET: docker-jwt-secret
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    networks:
      - user_network
    command: sh -c "npm install && npm run migrate && npm run dev"
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  user_network:
    driver: bridge